# Generated by Django 5.2.1 on 2025-05-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=244)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
